### ISSUE TITLE
MELPA project-persist-0.3 dependency fails

### ISSUE THREAD

**Issue by bit-twit** [rdallasgray/project-persist#4]
Hi,

The graphene package fails to install:  "Package `project-persist-0.3' is unavailable".
I looked for 'project-persist' in http://melpa.org/ and it is not there.

I saw you added 'project-persist-drawer' (that depends on project-persist-0.3) dependency to graphene -0.9.0 so maybe that's got smth to do with it.

Could you check it out ?

P..S: I'm kind of new to Emacs so maybe I'm doing smth wrong, although it worked before - my config is over here : https://github.com/bit-twit/emacs-config

**Comment by rdallasgray** [comment]
Thanks for the report -- I think this was to do with a faulty submodule declaration which I've now fixed. If the next Melpa build (should be in an hour or so) doesn't fix it for you, can you let me know?

**Comment by bit-twit** [comment]
I just tried it, project-persist is still not present on MELPA.

**Comment by rdallasgray** [comment]
OK, thanks. I'll raise an issue on Melpa and ask them to rebuild it manually.

**Comment by rdallasgray** [comment]
https://github.com/milkypostman/melpa/issues/2903

**Comment by bit-twit** [comment]
Hey.
It's fixed.

Thanks a lot :).
